<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.92.1" />


<title>Palmer Penguins visulization  - A Hugo website</title>
<meta property="og:title" content="Palmer Penguins visulization  - A Hugo website">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/rstudio/blogdown">GitHub</a></li>
    
    <li><a href="https://twitter.com/rstudio">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">5 min read</span>
    

    <h1 class="article-title">Palmer Penguins visulization </h1>

    
    <span class="article-date">2022-02-09</span>
    

    <div class="article-content">
      
<script src="/2022/02/09/palmer-penguins-visulization/index_files/header-attrs/header-attrs.js"></script>


<div id="palmer-penguins" class="section level2">
<h2>Palmer Penguins</h2>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.6     v dplyr   1.0.7
## v tidyr   1.2.0     v stringr 1.4.0
## v readr   2.1.2     v forcats 0.5.1</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(palmerpenguins)
glimpse(penguins)</code></pre>
<pre><code>## Rows: 344
## Columns: 8
## $ species           &lt;fct&gt; Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel~
## $ island            &lt;fct&gt; Torgersen, Torgersen, Torgersen, Torgersen, Torgerse~
## $ bill_length_mm    &lt;dbl&gt; 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, ~
## $ bill_depth_mm     &lt;dbl&gt; 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, ~
## $ flipper_length_mm &lt;int&gt; 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186~
## $ body_mass_g       &lt;int&gt; 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, ~
## $ sex               &lt;fct&gt; male, female, female, NA, female, male, female, male~
## $ year              &lt;int&gt; 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~</code></pre>
<blockquote>
<p>library(tidyverse)
– Attaching packages —————- tidyverse 1.3.1 –
v ggplot2 3.3.5 v purrr 0.3.4
v tibble 3.1.6 v dplyr 1.0.7
v tidyr 1.2.0 v stringr 1.4.0
v readr 2.1.2 v forcats 0.5.1
– Conflicts ——————- tidyverse_conflicts() –
x dplyr::filter() masks stats::filter()
x dplyr::lag() masks stats::lag()</p>
<p>library(tidyverse)</p>
<p>library(palmerpenguins)
Error in library(palmerpenguins) :
there is no package called ‘palmerpenguins’
library(tidyverse)
library(palmerpenguins)
Error in library(palmerpenguins) :
there is no package called ‘palmerpenguins’
glimpse(penguins)
Error in glimpse(penguins) : object ‘penguins’ not found
install.packages(“palmerpenguins”)
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:</p>
</blockquote>
<p><a href="https://cran.rstudio.com/bin/windows/Rtools/" class="uri">https://cran.rstudio.com/bin/windows/Rtools/</a>
Installing package into ‘C:/Users/cmsan/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL ‘<a href="https://cran.rstudio.com/bin/windows/contrib/4.1/palmerpenguins_0.1.0.zip" class="uri">https://cran.rstudio.com/bin/windows/contrib/4.1/palmerpenguins_0.1.0.zip</a>’
Content type ‘application/zip’ length 3003085 bytes (2.9 MB)
downloaded 2.9 MB</p>
<p>package ‘palmerpenguins’ successfully unpacked and MD5 sums checked</p>
<p>The downloaded binary packages are in
C:3n2_packages
&gt;
&gt; library(tidyverse)
&gt; library(palmerpenguins)
&gt; glimpse(penguins)
Rows: 344
Columns: 8
$ species <fct> Adelie, Adelie, Adelie, ~
$ island <fct> Torgersen, Torgersen, To~
$ bill_length_mm <dbl> 39.1, 39.5, 40.3, NA, 36~
$ bill_depth_mm <dbl> 18.7, 17.4, 18.0, NA, 19~
$ flipper_length_mm <int> 181, 186, 195, NA, 193, ~
$ body_mass_g <int> 3750, 3800, 3250, NA, 34~
$ sex <fct> male, female, female, NA~
$ year <int> 2007, 2007, 2007, 2007, ~
&gt;
&gt;
&gt; ## Scatter plot
&gt; ggplot(data = penguins,
+ mapping = aes(x = bill_depth_mm, y = bill_length_mm,
+ colour = species)) +
+ geom_point() +
+ labs(title = “Bill depth and length”,
+ subtitle = “Dimensions for Adelie, Chinstrap, and Gentoo Penguins”,
+ x = “Bill depth (mm)”, y = “Bill length (mm)”,
+ colour = “Species”)
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; library(tidyverse)
&gt; library(palmerpenguins)
&gt; glimpse(penguins)
Rows: 344
Columns: 8
$ species <fct> Adelie, Adelie, Adelie, ~
$ island <fct> Torgersen, Torgersen, To~
$ bill_length_mm <dbl> 39.1, 39.5, 40.3, NA, 36~
$ bill_depth_mm <dbl> 18.7, 17.4, 18.0, NA, 19~
$ flipper_length_mm <int> 181, 186, 195, NA, 193, ~
$ body_mass_g <int> 3750, 3800, 3250, NA, 34~
$ sex <fct> male, female, female, NA~
$ year <int> 2007, 2007, 2007, 2007, ~
&gt; ggplot(data = penguins,
+ mapping = aes(x = bill_depth_mm, y = bill_length_mm,
+ colour = species)) +
+ geom_point() +
+ labs(title = “Bill depth and length”,
+ subtitle = “Dimensions for Adelie, Chinstrap, and Gentoo Penguins”,
+ x = “Bill depth (mm)”, y = “Bill length (mm)”,
+ colour = “Species”)
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; ggplot(data = penguins,
+ mapping = aes(x = bill_depth_mm,
+ y = bill_length_mm,
+ colour = species)) +
+ geom_point() +
+ labs(title = “Bill depth and length”,
+ subtitle = “Dimensions for Adelie, Chinstrap, and Gentoo Penguins”,
+ x = “Bill depth (mm)”, y = “Bill length (mm)”,
+ colour = “Species”,
+ caption = “Source: Palmer Station LTER / palmerpenguins package”) +
+ scale_colour_viridis_d()
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; Start with the penguins data frame, map bill depth to the x-axis and map bill length to the y-axis. Represent each observation with a point and map species to the colour of each point. Title the plot “Bill depth and length”, add the subtitle “Dimensions for Adelie, Chinstrap, and Gentoo Penguins”, label the x and y axes as “Bill depth (mm)” and “Bill length (mm)”, respectively, label the legend “Species”, and add a caption for the data source. Finally, use a discrete colour scale that is designed to be perceived by viewers with common forms of colour blindness.
Error: unexpected symbol in “Start with”
&gt; ## Aesthetics
&gt; ggplot(penguins,
+ aes(x = bill_depth_mm,
+ y = bill_length_mm,
+ colour = species,
+ shape = species,
+ size = body_mass_g,
+ alpha = flipper_length_mm)) +
+ geom_point() +
+ scale_colour_viridis_d()
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; ## Faceting
&gt; ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +
+ geom_point() +
+ facet_grid(species ~ island)
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +
+ geom_point() +
+ facet_grid(species ~ sex)
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +
+ geom_point() +
+ facet_wrap(~ species)
Warning message:
Removed 2 rows containing missing values (geom_point).
&gt; ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +
+ geom_point() +
+ facet_wrap(~ species, ncol = 2)
Warning message:
Removed 2 rows containing missing values (geom_point).</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

